// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DeleteAddTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void deleteAddTest() {
    driver.get("http://localhost:4200/quiz");
    driver.manage().window().setSize(new Dimension(1346, 708));
    driver.findElement(By.cssSelector(".mat-list-item:nth-child(3) > .mat-list-item-content")).click();
    driver.findElement(By.cssSelector(".input-group:nth-child(1) > .form-control")).click();
    driver.findElement(By.cssSelector(".input-group:nth-child(1) > .form-control")).sendKeys("1*5=?");
    driver.findElement(By.cssSelector(".input-group:nth-child(2) > .form-control")).click();
    driver.findElement(By.cssSelector(".input-group:nth-child(2) > .form-control")).sendKeys("0");
    driver.findElement(By.cssSelector(".input-group:nth-child(3) > .form-control")).click();
    driver.findElement(By.cssSelector(".input-group:nth-child(3) > .form-control")).sendKeys("1");
    driver.findElement(By.cssSelector(".input-group:nth-child(4) > .form-control")).click();
    driver.findElement(By.cssSelector(".input-group:nth-child(4) > .form-control")).sendKeys("4");
    driver.findElement(By.cssSelector(".input-group:nth-child(5) > .form-control")).click();
    driver.findElement(By.cssSelector(".input-group:nth-child(5) > .form-control")).sendKeys("5");
    driver.findElement(By.cssSelector(".input-group:nth-child(6) > .form-control")).click();
    driver.findElement(By.cssSelector(".input-group:nth-child(6) > .form-control")).sendKeys("3");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.cssSelector(".mat-list-item:nth-child(4) > .mat-list-item-content")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) .btn")).click();
  }
}
